### ISSUE TITLE
Support Glibc

### ISSUE THREAD

**Issue by liqinggd** [occlum/occlum#214]
Currently, Only musl-based applications can run on Occlum, many Linux distributions use Glibc as the C Library. Applications must be recompiled with `occlum-gcc` to use Occlum. To overcome this inconvenience, we should support Glibc.

**Comment by liqinggd** [comment]
### Tasks
- [ ] Redirect glibc syscalls into Occlum
  + [ ] Modify glibc's syscall's asm code, to make syscall jumping into Occlum's syscall handler
  + [ ] Add posix_spawn support
- [ ] Occlum should be compatible with musl and glibc
  + [ ] Parse the executable's header, and get the ldso's path from the `INTERP` segment, and load the required ldso file (i.e., musl's ld or glibc's ld). If the exec file is compiled with musl, load musl's ldso, if the file is compiled with glibc, load glibc's ldso
  + [ ] Check if the executable is PIE enabled, if not, just exit with error
  + [ ] Modify test cases to to compatible with musl and glibc
